### ISSUE TITLE
Update outdated packages via Dependabot

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/eslint-config-stylelint#90]
The last commit via Dependabot is 8cac1b2eb23646a98cb631accd3f6e2ca5e0db1c (24 days ago), but I've noticed the following outdated packages:

```console
$ npm outdated
Package                        Current   Wanted  Latest  Location
eslint                           7.3.1    7.9.0   7.9.0  eslint-config-stylelint
eslint-config-prettier          6.10.1   6.11.0  6.11.0  eslint-config-stylelint
eslint-plugin-eslint-comments    3.1.2    3.2.0   3.2.0  eslint-config-stylelint
eslint-plugin-jest              23.8.2  23.20.0  24.0.2  eslint-config-stylelint
np                               6.2.3    6.5.0   6.5.0  eslint-config-stylelint
```

I'd like to update the packages to use new rules, but Dependabot seems not working. 🤔 

So, what about migrating GitHub powered Dependabot (using `.github/dependabot.yml`)? See the doc for details:
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

**Comment by hudochenkov** [comment]
Sure, why not.

More info about migration: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview

You might not see any updates, because Dependabot runs once per month in this repository.

I think you should have access to dependabot.com settings. If not, let me know.

**Comment by jeddy3** [comment]
SGTM.

It'd be great if we could migrate to the new Dependabot at the stylelint org level (e.g. put a config [here](https://github.com/stylelint/.github so that it's centrally managed like the dependabot.com settings), but it looks like we can't. So, let's go ahead and add a `.github/dependabot.yml` to this repo.

**Comment by ybiquitous** [comment]
@hudochenkov Thanks, I can view this repository setting on Dependabot.com. 👍 

@jeddy3 Thanks, I will try it. 💪

**Comment by ybiquitous** [comment]
I clicked **Create config file** button on Dependabot.com, then PR #91 is created automatically!

<img width="687" alt="image" src="https://user-images.githubusercontent.com/473530/94331343-a308d180-0006-11eb-9909-0553a3f9838f.png">

**Comment by ybiquitous** [comment]
Now, we have completed to migrate to `.github/dependabot.yml` (#91)

https://github.com/stylelint/eslint-config-stylelint/blob/1329692918dde94c3ef99a4bbec299cc70fbc719/.github/dependabot.yml#L1

Also, we can run Dependabot manually via **"Check for updates"** button on https://github.com/stylelint/eslint-config-stylelint/network/updates/

<img width="927" alt="image" src="https://user-images.githubusercontent.com/473530/94948498-6400e180-051a-11eb-9bf5-bdc711540943.png">

**Comment by ybiquitous** [comment]
Done! 🎉 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/473530/94949153-6e6fab00-051b-11eb-8810-eff793a17654.png">
